"""init schema

Revision ID: 98d0799e5eb6
Revises: 
Create Date: 2026-03-02 15:58:28.045538
"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '98d0799e5eb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_files_uploaded_at'), 'cv_files', ['uploaded_at'], unique=False)
    op.create_table('job_metadata',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('employer', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('ad_type', sa.String(), nullable=True),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text_snippet', sa.Text(), nullable=True),
    sa.Column('image_file', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_metadata_created_at'), 'job_metadata', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_metadata_ref'), 'job_metadata', ['ref'], unique=False)
    op.create_table('last_query',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('profile_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_table('ranked_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('employer', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('skills_found', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overlap', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('match_percent', sa.Float(), nullable=True),
    sa.Column('baseline_match_percent', sa.Float(), nullable=True),
    sa.Column('job_skill_count', sa.Integer(), nullable=True),
    sa.Column('user_skill_count', sa.Integer(), nullable=True),
    sa.Column('text_excerpt', sa.Text(), nullable=True),
    sa.Column('text_full', sa.Text(), nullable=True),
    sa.Column('must_have_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nice_to_have_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('core_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('matched_must_have', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_must_have', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('must_have_gate_pass', sa.Boolean(), nullable=True),
    sa.Column('matched_nice_to_have', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weighted_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('explanations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranked_jobs_created_at'), 'ranked_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ranked_jobs_ref'), 'ranked_jobs', ['ref'], unique=False)
    op.create_table('trend_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.Column('job_count', sa.Integer(), nullable=False),
    sa.Column('skill_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('role_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_history_ran_at'), 'trend_history', ['ran_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_salt', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trend_history_ran_at'), table_name='trend_history')
    op.drop_table('trend_history')
    op.drop_index(op.f('ix_ranked_jobs_ref'), table_name='ranked_jobs')
    op.drop_index(op.f('ix_ranked_jobs_created_at'), table_name='ranked_jobs')
    op.drop_table('ranked_jobs')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('last_query')
    op.drop_index(op.f('ix_job_metadata_ref'), table_name='job_metadata')
    op.drop_index(op.f('ix_job_metadata_created_at'), table_name='job_metadata')
    op.drop_table('job_metadata')
    op.drop_index(op.f('ix_cv_files_uploaded_at'), table_name='cv_files')
    op.drop_table('cv_files')
    # ### end Alembic commands ###
